# Generated by Django 5.0.3 on 2024-03-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('char', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('definitions', models.TextField(max_length=10000)),
                ('pinyin', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
